#!/bin/bash

# Switch to main branch
git checkout main

# Merge bug-fix-typo branch into main
git merge bug-fix-typo

# Expected output:
# Updating [commit-hash]..[commit-hash]
# Fast-forward
#  1 file changed, [insertions] insertion(+), [deletions] deletion(-)
